package dreamy

import (
	"fmt"
	"strings"

	"github.com/PuerkitoBio/goquery"

	"github.com/linuxnoodle/webfictionpoller/internal/models"
)

// FetchSeriesMetadata implements plugin.SeriesLister. Scrapes the story
// page for title, author, synopsis, cover image URL.
func (p *Provider) FetchSeriesMetadata(rawURL string) (models.Series, error) {
	slug, ok := slugFromURL(rawURL)
	if !ok {
		return models.Series{}, fmt.Errorf("dreamy: not a novel URL: %s", rawURL)
	}
	doc, err := p.fetchDoc(storyURL(slug))
	if err != nil {
		return models.Series{}, err
	}

	title := textOrEmpty(doc.Find("h1"))
	if title == "" {
		return models.Series{}, fmt.Errorf("dreamy: no <h1> title found at %s", rawURL)
	}

	return models.Series{
		Title:        title,
		Author:       parseAuthor(doc),
		SourceURL:    storyURL(slug),
		ProviderName: providerName,
		Summary:      parseSynopsis(doc),
		ImageURL:     parseCoverURL(doc, title),
		Status:       "active",
		Rating:       models.UnratedRating,
	}, nil
}

// parseAuthor finds the author when the site exposes it inline. Empirically
// only some stories show "by X" under the title; others (e.g. rev) have no
// visible author element and the field is left empty. The Next.js __next_f
// JSON sometimes carries it but extracting from there is brittle; we accept
// empty author when the DOM doesn't expose it rather than guess.
//
// Verified shape (imc):
//   <h1 ...>Title</h1>
//   <p class="text-xs ...">by <span class="font-medium">Author</span></p>
func parseAuthor(doc *goquery.Document) string {
	// h1's adjacent <p> containing "by".
	if span := doc.Find("h1 ~ p:contains('by ') span").First(); span.Length() > 0 {
		if a := textOrEmpty(span); a != "" {
			return a
		}
	}
	// Broader fallback: any <p> with "by " followed by a span.font-medium.
	if span := doc.Find("p:contains('by ') span.font-medium").First(); span.Length() > 0 {
		return textOrEmpty(span)
	}
	return ""
}

// parseSynopsis pulls the synopsis from <meta name="description">. This tag
// is present on every story page (set by Next.js metadata API) and contains
// the same synopsis text shown in the UI's synopsis block. Far more stable
// than trying to identify the synopsis <p> in the body (which sits among
// other <p> elements with similar lengths).
func parseSynopsis(doc *goquery.Document) string {
	if desc, _ := doc.Find(`meta[name="description"]`).First().Attr("content"); desc != "" {
		return strings.TrimSpace(desc)
	}
	// Fallback: og:description carries the same text.
	if desc, _ := doc.Find(`meta[property="og:description"]`).First().Attr("content"); desc != "" {
		return strings.TrimSpace(desc)
	}
	return ""
}

// parseCoverURL finds the cover image via og:image meta tag (stable) first,
// then falls back to scanning <img> tags. The og:image tag is generated by
// Next.js metadata API and present on every story page.
func parseCoverURL(doc *goquery.Document, title string) string {
	if src, _ := doc.Find(`meta[property="og:image"]`).First().Attr("content"); src != "" {
		return src
	}
	// Fallback: any supabase cover URL.
	src, _ := doc.Find("img[src*='supabase.dreamy-translations.com/storage/v1/object/public/covers']").First().Attr("src")
	return src
}
